### ISSUE TITLE
[BUG] Problem displaying theme layout correctly after last update

### ISSUE THREAD

**Issue by rimatech987** [gethinode/hinode#253]
**Describe the bug**
I am having problems displaying the layout of this theme after updating it.
I still have the old versions and do not have this problem.

**To reproduce**
1. hugo new site xxx
2. git clone git clone https://github.com/gethinode/hinode.git my-hinode-site && cd my-hinode-site (also applies to child one)
3. npm install
4. npm run start

**Expected behavior**
I expect it to be fixed as before.

**Log file**
-

**Screenshots**
![Layout_pic](https://github.com/gethinode/hinode/assets/87300172/68607b06-b9c1-4b6f-ac73-838de1d518f5)

**Environment (please complete the following information):**
 - Hinode version: v0.12.12
 - Host OS: Fedora Linux 37 (Workstation Edition)
 - Node version: v18.15.0
 - Hugo version: hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192 linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
 - Browser: Mozilla Firefox 112.0.2 (64 bit) - Chromium 113.0.5672.63 (64 bit)

**Comment by markdumay** [comment]
That's odd, looks like the CSS isn't applied at all. The site has been deployed successfully according to the logs, see https://demo.gethinode.com/en/. I don't have any issues on my local machine either. A few questions:
- Have you tried clearing your browser cache?
- Does your browser give any errors/warnings?
- Does https://demo.gethinode.com/en/ render correctly on your machine?

**Comment by rimatech987** [comment]
Yes, I always wipe my browser data on exit (cache, cookies, etc.), so it's not a problem with my browser, as I can view an old version of your project perfectly well. In fact, I did a fork 4 months ago (not updated) and it works perfectly.

The website https://demo.gethinode.com/en/ works

I think it is due to this:

![Browser_error](https://github.com/gethinode/hinode/assets/87300172/36b676ae-9ef4-4ffd-909b-82f83ad8d58b)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

What should I do?

**Comment by markdumay** [comment]
At first glance, it seems an invalid path is defined for the main.css file. It should be ‘/css/main.css‘ instead of ‘/en/css/main.css’.  It looks like a relative path instead of an absolute path is used somehow. I’m not behind a computer right now, but perhaps this is a clue?On 14 May 2023, at 15:51, rimatech987 ***@***.***> wrote:﻿
Yes, I always wipe my browser data on exit (cache, cookies, etc.), so it's not a problem with my browser, as I can view an old version of your project perfectly well. In fact, I did a fork 4 months ago (not updated) and it works perfectly.
The website https://demo.gethinode.com/en/ works
I think it is due to this:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default
What should I do?

**Comment by markdumay** [comment]
I was finally able to recreate the issue. The bug appeared in local development mode only (`npm run start`). I usually run `npm run start:prod` instead, as it is faster and mimics production. It should now be fixed in [v0.13.2](https://github.com/gethinode/hinode/releases/tag/v0.13.2).

**Comment by Davidocity** [comment]
Hi Mark - The bug (as shown in the original screenshot above) still appears in the child theme when using `npm run start` but is not present when using `npm run start:prod`. No issues found with the main theme when tested a few minutes ago. Awesome Hugo theme BTW.

**Comment by markdumay** [comment]
Glad you like the theme! Dependabot should pick up the update soon and merge it with the child repo’s main branch automatically. If not, I’ll push a manual update tomorrow. On 16 May 2023, at 16:47, Davidocity ***@***.***> wrote:﻿
Hi Mark - The bug (as shown in the original screenshot above) still appears in the child theme when using npm run start but is not present when using npm run start:prod. No issues found with the main theme when tested a few minutes ago. Awesome Hugo theme BTW.

**Comment by rimatech987** [comment]
Yes I confirm, it now also works in local development mode.
